#include "file_readers/image_files/raw_data.hpp"
#include "file_readers/image_files/bmp_reader.hpp"
#include "file_readers/file.hpp"

#include <optional>
#include <stdexcept>

/* Creates a file file_name, and writes in it the resolution of the image, the number of rays used to generate it,
   and the raw data of the matrix
   Returns true if the operation was successful */
/* Format:

   width:1366 height:768 number_of_rays:10
   2550.0000000000 2000.0000000000 1367.4666666666
   ...
   
   width * height of 3 doubles (red, green, blue) separated by spaces,
   pixel (i,j) at line j*width + i
   line k representing pixel (k % width, k / width)
*/
// format = 0: decimal representations written in sequence, one by line
// format = 1: binary values written in sequence
exit_status export_raw(const std::string& file_name, const image& image, const unsigned int format) {

    file f(file_name, "w");

    try {
        const auto [ width, height ] = image.data.get_dimensions();
        
        const exit_status status = f.printf("width:%u height:%u number_of_rays:%u format:%u pixel_size:%zu\n",
            width, height, image.number_of_samples, format, sizeof(rt::color));

        if (status == exit_status::Failure) {
            printf("Writing error at first line of %s\n", file_name.c_str());
            throw std::runtime_error("");
        }

        switch (format) {
            case 0:
                for (int j = height - 1; j >= 0; j--) {
                    const matrix::const_row row = image.data[j];
                    for (const rt::color& c : row) {
                        const auto [ r, g, b ] = c;
                        f.printf("%lf %lf %lf\n", r, g, b);
                    }
                }
                break;
            case 1: {
                const std::size_t buffer_size = image.width() * image.height();
                const std::unique_ptr<rt::color> buffer_container(new rt::color[buffer_size]);
                rt::color* buffer_start = buffer_container.get();

                std::size_t index = 0;
                const std::size_t row_length_bin = width * sizeof(rt::color);
                for (const matrix::const_row row : image.data) {
                    std::memcpy(buffer_start + index, row.data(), row_length_bin);
                    index += width;
                }

                const std::span buffer = { reinterpret_cast<const rt::color*>(buffer_start), buffer_size };
                const exit_status status = f.write(buffer);
                throw_if_failure(status, "Could not write in file");
                break;
            }
            default:
                throw std::runtime_error("Incorrect format");
        }

        return exit_status::Success;
    }
    catch(const std::exception& e) {
        printf("%s", e.what());
        return exit_status::Failure;
    }
}

static const rt::color* read_raw_file_content(const file& f, const unsigned int format,
    const unsigned int pixel_size, const unsigned int buffer_size) {

    if (format != 1)
        throw std::runtime_error("read_raw_file_content: Incorrect format");

    if (f.length() < buffer_size * pixel_size)
        throw std::runtime_error("read_raw_file_content: Incorrect file size");
    
    const std::unique_ptr<rt::color> buffer_container(new rt::color[buffer_size]);
    rt::color* buffer_start = buffer_container.get();

    const exit_status status = f.read(std::span{ buffer_start, buffer_size });
    throw_if_failure(status, "Error reading color data");

    return buffer_start;
}

/* Reads a file file_name generated by export_raw, and returns a matrix with its content
   Writes the number of rays in the associated variable */
std::optional<image> read_raw(const std::string& file_name) {

    file f(file_name);

    try {
        unsigned int width, height, number_of_rays;
        unsigned int format = 0;
        std::size_t pixel_size = sizeof(rt::color);
        const int ret = f.scanf_count("width:%u height:%u number_of_rays:%u format:%u pixel_size:%zu\n",
            width, height, number_of_rays, format, pixel_size);

        if (ret < 3 || (format != 0 && format != 1)) {
            printf("Reading error at first line of file %s\n", file_name.c_str());
            throw std::runtime_error("");
        }

        image image(width, height);
        
        switch (format) {
            case 0: {
                for (int j = height - 1; j >= 0; j--) {
                    const matrix::row row = image.data[j];
                    for (rt::color& c : row) {
                        const auto [ r, g, b ] = f.scan<real, 3>();
                        c = rt::color(r, g, b);
                    }
                }
                break;
            }
            case 1: {
                const unsigned int buffer_size = width * height;
                const rt::color* buffer = read_raw_file_content(f, format, pixel_size, buffer_size);
                f.close();

                std::size_t index = 0;
                const std::size_t row_length_binary = width * pixel_size;
                for (const matrix::row row : image.data) {
                    std::memcpy(row.data(), buffer + index, row_length_binary);
                    index += width;
                }
                break;
            }
            default:
                break;
        }

        return image;

    }
    catch(const std::exception& e) {

        return std::nullopt;
    }
}

/* Combines the n files whose names are in the array source_file_names into one bmp file dest_bmp_name (extension .bmp)
   and one raw data file dest_raw_name (extension .rtdata)
   Returns true if the operation was successful */
exit_status combine_raw(const std::string& dest_bmp_name, const std::string& dest_raw_name,
    const std::span<const std::string> source_file_names, const float gamma) {

    const std::size_t nb_files = source_file_names.size();
    printf("Merging %zu file%s...\n", nb_files, (nb_files > 1) ? "s" : "");

    /* Determination of the size of the matrix */
    unsigned int width, height;
    {
        file f0(source_file_names[0]);
        const exit_status status = f0.scanf("width:%u height:%u", width, height);

        if (status == exit_status::Failure) {
            printf("Reading error at first line of file %s\n", source_file_names[0].c_str());
            return exit_status::Failure;
        }
    }

    image image(width, height, gamma);

    /* Adding the value of each file to matrix */
    for (const std::string& name : source_file_names) {

        file f(name);

        unsigned int width_k, height_k, number_of_rays_k;
        unsigned int format = 0;
        std::size_t pixel_size = sizeof(rt::color);
        const int ret = f.scanf_count("width:%u height:%u number_of_rays:%u format:%u pixel_size:%zu\n",
            width_k, height_k, number_of_rays_k, format, pixel_size);

        if (ret < 3 || (format != 0 && format != 1)) {
            printf("Reading error at first line of file %s\n", name.c_str());
            return exit_status::Failure;
        }

        if (width_k != width || height_k != height) {
            printf("Error, incorrect width or height in file %s\n", name.c_str());
            return exit_status::Failure;
        }

        switch (format) {
            case 0: {
                for (int j = height - 1; j >= 0; j--) {
                    const matrix::row row = image.data[j];
                    for (rt::color& color : row) {
                        const auto [ r, g, b ] = f.scan<real, 3>();
                        color += rt::color(r, g, b);
                    }
                }
                break;
            }
            case 1: {
                const unsigned int buffer_size = width * height;
                const rt::color* buffer = read_raw_file_content(f, format, pixel_size, buffer_size);
                f.close();
                
                for (int index = 0; const matrix::row row : image.data) {
                    for (rt::color& color : row) {
                        color += buffer[index];
                        index++;
                    }
                }
                break;
            }
            default:
                break;
        }

        image.increase_sample_count(number_of_rays_k);
    }

    /* Exporting the matrix as a bmp file */
    const exit_status success_bmp = write_bmp(dest_bmp_name, image);
    constexpr unsigned int DEFAULT_FORMAT = 1;
    const exit_status success_raw = export_raw(dest_raw_name, image, DEFAULT_FORMAT);

    if ((success_bmp && success_raw) == exit_status::Success)
        return exit_status::Success;
    
    if (success_bmp == exit_status::Failure)
        printf("Error in generating the bmp file %s\n", dest_bmp_name.c_str());
    if (success_raw == exit_status::Failure)
        printf("Error in generating the raw data file %s\n", dest_raw_name.c_str());

    return exit_status::Failure;
}