#include "file_readers/image_files/raw_data.hpp"
#include "file_readers/image_files/bmp_reader.hpp"
#include "file_readers/file.hpp"

#include <stdexcept>
#include <cstdlib>
#include <memory>
#include <cstring>

using enum raw_data::format;
using enum file_reader::error;

// format = 0: decimal representations written in sequence, one by line
// format = 1: binary values written in sequence
exit_status raw_data::export_data(const std::string& file_name, const image& image, const raw_data::format format) {

    file f(file_name, "w");

    try {
        const auto [ width, height ] = image.data.get_dimensions();
        
        const exit_status status = f.printf("width:%u height:%u number_of_rays:%u format:%u pixel_size:%zu\n",
            width, height, image.number_of_samples, format, sizeof(rt::color));

        throw_if_failure(status, "Writing error at first line of " + file_name + "\n");

        switch (format) {
            case Text:
                for (int j = height - 1; j >= 0; j--) {
                    const matrix::const_row row = image.data[j];
                    for (const rt::color& c : row) {
                        const auto [ r, g, b ] = c;
                        f.printf("%lf %lf %lf\n", r, g, b);
                    }
                }
                break;
            case Binary: {
                const std::size_t buffer_size = image.width() * image.height();
                const std::unique_ptr<rt::color[]> buffer_container(new rt::color[buffer_size]);
                rt::color* buffer_start = buffer_container.get();

                std::size_t index = 0;
                const std::size_t row_length_bin = width * sizeof(rt::color);
                for (const matrix::const_row row : image.data) {
                    std::memcpy(buffer_start + index, row.data(), row_length_bin);
                    index += width;
                }
                
                const std::span buffer = { reinterpret_cast<const rt::color*>(buffer_start), buffer_size };
                const exit_status status = f.write(buffer);
                throw_if_failure(status, "Could not write in file");
                break;
            }
        }

        return exit_status::Success;
    }
    catch(const std::exception& e) {
        printf("%s", e.what());
        return exit_status::Failure;
    }
}

static std::unique_ptr<rt::color[]> read_raw_file_content(const file& f, const raw_data::format format,
    const unsigned int pixel_size, const unsigned int buffer_size) {

    if (format != Binary) {
        printf("read_raw_file_content: Incorrect format\n");
        throw DataError;
    }

    if (f.length() < buffer_size * pixel_size) {
        printf("read_raw_file_content: Incorrect file size\n");
        throw DataError;
    }
    
    std::unique_ptr<rt::color[]> buffer(new rt::color[buffer_size]);
    
    const exit_status status = f.read(std::span{ buffer.get(), buffer_size });
    throw_if_failure(status, ReadingErrorData);

    return buffer;
}

/* Reads a file file_name generated by export_raw, and returns a matrix with its content
   Writes the number of rays in the associated variable */
std::expected<image, file_reader::error> raw_data::read_file(const std::string& file_name) {

    try {

        file f(file_name);

        unsigned int width, height, number_of_rays;
        unsigned int format_code = 0;
        std::size_t pixel_size = sizeof(rt::color);
        const int ret = f.scanf_count("width:%u height:%u number_of_rays:%u format:%u pixel_size:%zu\n",
            width, height, number_of_rays, format_code, pixel_size);

        if (ret < 3)
            throw ReadingErrorHeader;
        if (format_code != 0 && format_code != 1)
            throw DataError;
            
        const raw_data::format format = static_cast<raw_data::format>(format_code);

        image image(width, height);
        
        switch (format) {
            case Text: {
                for (int j = height - 1; j >= 0; j--) {
                    const matrix::row row = image.data[j];
                    for (rt::color& c : row) {
                        const auto [ r, g, b ] = f.scan<real, 3>();
                        c = rt::color(r, g, b);
                    }
                }
                break;
            }
            case Binary: {
                const unsigned int buffer_size = width * height;
                const std::unique_ptr<rt::color[]> buffer_container = read_raw_file_content(f, format, pixel_size, buffer_size);
                f.close();

                const rt::color* buffer = buffer_container.get();
                const std::size_t row_length_binary = width * pixel_size;

                std::size_t index = 0;
                for (const matrix::row row : image.data) {
                    std::memcpy(row.data(), buffer + index, row_length_binary);
                    index += width;
                }
                break;
            }
        }

        return image;

    }
    catch(file_reader::error e) {
        return std::unexpected(e);
    }
    catch(const std::exception&) {
        return std::unexpected(Other);
    }
}

/* Combines the n files whose names are in the array source_file_names into one bmp file dest_bmp_name (extension .bmp)
   and one raw data file dest_raw_name (extension .rtdata)
   Returns true if the operation was successful */
exit_status raw_data::combine_files(const std::string& dest_bmp_name, const std::string& dest_raw_name,
    const std::span<const std::string> source_file_names, const float gamma) {

    const std::size_t nb_files = source_file_names.size();
    printf("Merging %zu file%s...\n", nb_files, (nb_files > 1) ? "s" : "");

    try {

        /* Determination of the size of the matrix */
        unsigned int width, height;
        file f0(source_file_names[0]);
        const exit_status status = f0.scanf("width:%u height:%u", width, height);

        if (status == exit_status::Failure) {
            printf("Reading error at first line of file %s\n", source_file_names[0].c_str());
            throw ReadingErrorHeader;
        }

        image image(width, height, gamma);

        /* Adding the value of each file to matrix */
        for (const std::string& name : source_file_names) {

            file f(name);

            unsigned int width_k, height_k, number_of_rays_k;
            unsigned int format_code = 0;
            std::size_t pixel_size = sizeof(rt::color); // default value
            const int ret = f.scanf_count("width:%u height:%u number_of_rays:%u format:%u pixel_size:%zu\n",
                width_k, height_k, number_of_rays_k, format_code, pixel_size);

            const bool correct_format = format_code == 0 || format_code == 1;
            if (ret < 3 || not correct_format) {
                printf("Reading error at first line of file %s\n", name.c_str());
                throw (correct_format) ? ReadingErrorHeader : DataError;
            }

            if (width_k != width || height_k != height) {
                printf("Error, incorrect width or height in file %s\n", name.c_str());
                throw DataError;
            }

            const raw_data::format format = static_cast<raw_data::format>(format_code);

            switch (format) {
                case Text: {
                    for (int j = height - 1; j >= 0; j--) {
                        const matrix::row row = image.data[j];
                        for (rt::color& color : row) {
                            const auto [ r, g, b ] = f.scan<real, 3>();
                            color += rt::color(r, g, b);
                        }
                    }
                    break;
                }
                case Binary: {
                    const unsigned int buffer_size = width * height;
                    const std::unique_ptr<rt::color[]> buffer_container = read_raw_file_content(f, format, pixel_size, buffer_size);
                    f.close();

                    const rt::color* buffer = buffer_container.get();
                    
                    for (int index = 0; const matrix::row row : image.data) {
                        for (rt::color& color : row) {
                            color += buffer[index];
                            index++;
                        }
                    }
                    break;
                }
            }

            image.increase_sample_count(number_of_rays_k);
        }

        /* Exporting the matrix as a bmp file */
        const exit_status status_bmp = bmp::export_data(dest_bmp_name, image);

        constexpr format DEFAULT_FORMAT = Binary;
        const exit_status status_raw = export_data(dest_raw_name, image, DEFAULT_FORMAT);

        if ((status_bmp && status_raw) == exit_status::Failure) {
                
            if (status_bmp == exit_status::Failure)
                printf("Error in generating the bmp file %s\n", dest_bmp_name.c_str());
            if (status_raw == exit_status::Failure) 
                printf("Error in generating the raw data file %s\n", dest_raw_name.c_str());

            throw FileError;
        }

        return exit_status::Success;
    }
    catch (...) {
        return exit_status::Failure;
    }
}