#pragma once

#include "auxiliary/exit_status.hpp"
#include "image/image.hpp"

#include <optional>
#include <string>
#include <span>

class raw_data {

   public:
   
      enum class format : unsigned int {
         Text   = 0,
         Binary = 1
      };

      /* Creates a file file_name, and writes in it the resolution of the image, the number of rays used to generate it,
         and the raw data of the matrix */
      /* Format:

         Text
         width:1366 height:768
         number_of_rays:10
         2550.0000000000 2000.0000000000 1367.4666666666
         ...
         
         width * height rows of 3 doubles separated by spaces,
         pixel (i,j) at line j * width + i
         line k representing pixel (k % width, k / width)

         Binary
         width:1920 height:1080 number_of_rays:500 format:1 pixel_size:24
         Binary representation of the rows of the input image, stored consecutively, with no separator
      */
      static exit_status export_data(const std::string& file_name, const image& image, format format = format::Binary);

      /* Reads a file file_name generated by export_raw, and returns a matrix with its content
         Writes the number of rays in the associated variable */
      static std::optional<image> read_file(const std::string& file_name);

      /* Combines the n files whose names are in the array source_file_names into one bmp file dest_bmp_name (extension .bmp)
         and one raw data file dest_raw_name (extension .rtdata)
         Returns true if the operation was successful */
      static exit_status combine_files(const std::string& dest_bmp_name, const std::string& dest_raw_name,
         const std::span<const std::string> source_file_names, const float gamma = 1.0f);

};