#include "file_readers/raw_data.hpp"
#include "file_readers/bmp_reader.hpp"
#include "file_readers/file.hpp"

#include <optional>
#include <stdexcept>

/* Creates a file file_name, and writes in it the resolution of the image, the number of rays used to generate it,
   and the raw data of the matrix
   Returns true if the operation was successful */
/* Format:

   width:1366 height:768 number_of_rays:10
   2550.0000000000 2000.0000000000 1367.4666666666
   ...
   
   width * height of 3 doubles (red, green, blue) separated by spaces,
   pixel (i,j) at line j*width + i
   line k representing pixel (k % width, k / width)
*/
exit_status export_raw(const std::string& file_name, const image& image) {

    file f(file_name, "w");

    try {
        const auto [ width, height ] = image.data.get_dimensions();

        const exit_status status = f.printf("width:%u height:%u number_of_rays:%u\n", width, height, image.number_of_samples);
        if (status == exit_status::Failure) {
            printf("Writing error at first line of %s\n", file_name.c_str());
            throw std::runtime_error("");
        }

        for (const matrix::const_row row : image.data) {
            for (const rt::color& c : row) {
                const auto [ r, g, b ] = c;
                f.printf("%lf %lf %lf\n", r, g, b);
            }
        }

        return exit_status::Success;
    }
    catch(const std::exception& e) {
        printf("%s", e.what());
        return exit_status::Failure;
    }
}

/* Reads a file file_name generated by export_raw, and returns a matrix with its content
   Writes the number of rays in the associated variable */
std::optional<image> read_raw(const std::string& file_name) {

    file f(file_name);

    try {
        unsigned int width, height, number_of_rays;
        const exit_status status = f.scanf("width:%u height:%u number_of_rays:%u\n", width, height, number_of_rays);

        if (status == exit_status::Failure) {
            printf("Reading error at first line of file %s\n", file_name.c_str());
            throw std::runtime_error("");
        }

        image image(width, height);
        
        for (const matrix::row row : image.data) {
            for (rt::color& c : row) {
                const auto [ r, g, b ] = f.scan<real, 3>();
                c = rt::color(r, g, b);
            }
        }

        return image;

    }
    catch(const std::exception& e) {

        return std::nullopt;
    }
}

/* Combines the n files whose names are in the array source_file_names into one bmp file dest_bmp_name (extension .bmp)
   and one raw data file dest_raw_name (extension .rtdata)
   Returns true if the operation was successful */
exit_status combine_raw(const std::string& dest_bmp_name, const std::string& dest_raw_name,
    const std::span<const std::string> source_file_names, const float gamma) {

    printf("Merging %lu files...\n", source_file_names.size());

    /* Determination of the size of the matrix */
    unsigned int width, height;
    {
        file f0(source_file_names[0]);
        const exit_status status = f0.scanf("width:%u height:%u", width, height);

        if (status == exit_status::Failure) {
            printf("Reading error at first line of file %s\n", source_file_names[0].c_str());
            return exit_status::Failure;
        }
    }

    image image(width, height, gamma);

    /* Adding the value of each file to matrix */
    for (const std::string& name : source_file_names) {

        file f(name);

        unsigned int width_k, height_k, number_of_rays_k;
        const exit_status status = f.scanf("width:%u height:%u number_of_rays:%u\n", width_k, height_k, number_of_rays_k);

        if (status == exit_status::Failure) {
            printf("Reading error at first line of file %s\n", name.c_str());
            return exit_status::Failure;
        }

        if (width_k != width || height_k != height) {
            printf("Error, incorrect width or height in file %s\n", name.c_str());
            return exit_status::Failure;
        }

        image.increase_sample_count(number_of_rays_k);

        for (const matrix::row row : image.data) {
            for (rt::color& color : row) {
                const auto [ r, g, b ] = f.scan<real, 3>();
                color += rt::color(r, g, b);
            }
        }
    }

    /* Exporting the matrix as a bmp file */
    const exit_status success_bmp = write_bmp (dest_bmp_name, image);
    const exit_status success_raw = export_raw(dest_raw_name, image);

    if ((success_bmp && success_raw) == exit_status::Success)
        return exit_status::Success;
    
    if (success_bmp == exit_status::Failure)
        printf("Error in generating the bmp file %s\n", dest_bmp_name.c_str());
    if (success_raw == exit_status::Failure)
        printf("Error in generating the raw data file %s\n", dest_raw_name.c_str());

    return exit_status::Failure;
}