#pragma once

#include "auxiliary/exit_status.hpp"
#include "image/image.hpp"

#include <optional>
#include <string>
#include <span>


/* Creates a file file_name, and writes in it the resolution of the image, the number of rays used to generate it,
   and the raw data of the matrix
   Returns true if the operation was successful */
/* Format:

   width:1366 height:768
   number_of_rays:10
   2550.0000000000 2000.0000000000 1367.4666666666
   ...
   
   width * height of 3 doubles separated by spaces,
   pixel (i,j) at line j*width + i
   line k representing pixel (k % width, k / width)
*/
exit_status export_raw(const std::string& file_name, const image& image);

/* Reads a file file_name generated by export_raw, and returns a matrix with its content
   Writes the number of rays in the associated variable */
std::optional<image> read_raw(const std::string& file_name);

/* Combines the n files whose names are in the array source_file_names into one bmp file dest_bmp_name (extension .bmp)
   and one raw data file dest_raw_name (extension .rtdata)
   Returns true if the operation was successful */
exit_status combine_raw(const std::string& dest_bmp_name, const std::string& dest_raw_name,
   const std::span<const std::string> source_file_names, const float gamma = 1.0f);
