#include "scene/objects/quad.hpp"

#include "auxiliary/utils.hpp"

#include <iostream>

using enum det_case;

void set_up_det(const rt::vector& v1, const rt::vector& v2, const rt::vector& v3,
    // output parameters
    real& det12, real& det23, det_case& case_det) {

    for (det_case det_case : { XY, XZ, YZ }) {
        const real det = compute_det_2d(v1, v2, det_case);
        if (is_not_zero(det)) {
            det12    = det;
            det23    = compute_det_2d(v3, v2, det_case);
            case_det = det_case;
            return;
        }
    }

    det12    = 0.0_r;
    det23    = 0.0_r;
    case_det = Error;
}
        
// Constructor from four points
// We do not check whether the four points are coplanar
quad::quad(const rt::vector& p0, const rt::vector& p1, const rt::vector& p2, const rt::vector& p3, 
    const unsigned int material_index, const unsigned int texture_info_index)

    : object(p0, material_index, texture_info_index) {

    v1 = p1 - p0;
    v2 = p2 - p0;
    v3 = p3 - p0;
    const rt::vector n = (v1 ^ v2);
    const real n_norm = n.norm();
    normal = n / n_norm;
    vn0 = normal;
    d = - (normal | p0);

    set_up_det(v1, v2, v3, det12, det23, case_det);

    ratio = (n_norm / (n_norm + (v2 ^ v3).norm()));
}

// Constructor from four points with vertex normals
quad::quad(const rt::vector& p0, const rt::vector& p1, const rt::vector& p2, const rt::vector& p3,
    const rt::vector& vn0init, const rt::vector& vn1, const rt::vector& vn2, const rt::vector& vn3,
    const unsigned int material_index, const unsigned int texture_info_index)

    : quad(p0, p1, p2, p3, material_index, texture_info_index) {
    
    vn0     = vn0init.unit();
    vn1mvn0 = (vn1.unit()) - vn0;
    vn2mvn0 = (vn2.unit()) - vn0;
    vn3mvn0 = (vn3.unit()) - vn0;
}

// Constructor from four points with normal mapping enabled
quad::quad(const rt::vector& p0, const rt::vector& p1, const rt::vector& p2, const rt::vector& p3,
    const unsigned int material_index, const unsigned int texture_info_index, const bool normal_mapping,
    texture_info& info)

    : quad(p0, p1, p2, p3, material_index, texture_info_index) {
    
    if (normal_mapping) {
        
        /* Same as triangle */
    
        const std::vector<real>& uvc = info.uv_coordinates;
        // uvc = (u0, v0, u1, v1, u2, v2)
        const real x1 = uvc[2] - uvc[0];
        const real x2 = uvc[4] - uvc[0];
        const real y1 = uvc[3] - uvc[1];
        const real y2 = uvc[5] - uvc[1];
        const real r = 1.0_r / (x1 * y2 - x2 * y1);
        const rt::vector t = r * ( y2 * v1 + -y1 * v2);
        const rt::vector b = r * (-x2 * v1 +  x1 * v2);
        info.set_tangent_space(t.unit(), b.unit());
    }
}

// Constructor from four points with vertex normals and normal mapping enabled
quad::quad(const rt::vector& p0, const rt::vector& p1, const rt::vector& p2, const rt::vector& p3,
    const rt::vector& vn0init, const rt::vector& vn1, const rt::vector& vn2, const rt::vector& vn3,
    const unsigned int material_index, const unsigned int texture_info_index, const bool normal_mapping,
    texture_info& info)

    : quad(p0, p1, p2, p3, material_index, texture_info_index, normal_mapping, info) {

    vn0     = vn0init.unit();
    vn1mvn0 = (vn1.unit()) - vn0;
    vn2mvn0 = (vn2.unit()) - vn0;
    vn3mvn0 = (vn3.unit()) - vn0;
}

/* Returns the barycenter of the quad */
inline rt::vector quad::get_barycenter() const {
    return position + ((v1 + v2 + v3) / 4);
}

/* Intersection determination */
real quad::measure_distance(const ray& r) const {
    
    // Intersection between the ray and the triangle plane
    const real pdt  = (normal | r.direction);  // ax + by + cz
    const real upln = (normal | r.origin) + d; // aX + bY + cZ + d
    
    // If -upln/pdt > 0, it is our solution t, otherwise the plane is either parallel (pdt == 0) or "behind" the plane (-upln/pdt < 0)
    if (std::signbit(pdt) == std::signbit(upln))
        return infinity;

    const real t = - upln / pdt;

    /* See triangle intersection.
       Here we check if the points lies in the triangle generated by v1, v2
       (by solving the system for x, y, and if they are colinear when projected on the plane z = 0, for x, z),
       if it does not, we check if it lies in the triangle generated by v2, v3 in the same way. */

	const rt::vector c = r.extend(t) - position;
    
    const real detv2 = compute_det_2d(c, v2, case_det);
    const real l1 = detv2 / det12;

    if (is_between_zero_and_one(l1)) {
        const real l2 = compute_det_2d(v1, c, case_det) / det12;
        if (is_positive(l2) && (l1 + l2) <= 1.0_r)
            return t;
    }

    const real l1a = detv2 / det23;
    if (not is_between_zero_and_one(l1a))
        return infinity;
        
    const real l2a = compute_det_2d(v3, c, case_det) / det23;
    return (is_positive(l2a) && l1a + l2a <= 1.0_r) ? t : infinity;
}

/* Returns the barycentric info (l1, l2, lower_triangle):
   (0 <= l1, l2 <= 1)
   p = position + l1 * v1 + l2 * v2 if lower_triangle == true,
   or
   p = position + l1 * v3 + l2 * v2 otherwise
*/
barycentric_info quad::get_barycentric(const rt::vector& p) const {

    const rt::vector c = p - position;

    const real detv2 = compute_det_2d(c, v2, case_det);
    const real l1 = detv2 / det12;
    
    if (is_between_zero_and_one(l1)) {
        
        const real l2 = compute_det_2d(v1, c, case_det) / det12;
        if (is_positive(l2) && l1 + l2 <= 1.0_r)
            return barycentric_info(l1, l2, object_type::Quad, side::LowerTriangle);
    }

    const real l1a = detv2 / det23;
    const real l2a = compute_det_2d(v3, c, case_det) / det23;
    
    return barycentric_info(l1a, l2a, object_type::Quad, side::HigherTriangle);

}

inline rt::vector quad::get_interpolated_normal(const barycentric_info& bary) const {
    
    const rt::vector& vn = (bary.triangle_side == side::LowerTriangle) ? vn1mvn0 : vn3mvn0;
    const auto [ l1, l2 ] = bary.l;
    return fma(vn2mvn0, l2, fma(vn, l1, vn0));
}

hit quad::compute_intersection(const ray& r, const real t) const {

    const rt::vector p = r.extend(t);
    const object* pt_obj = this;
    const ray* pt_ray = &r;

    if constexpr (SHADING == shading::SmoothShading) {
        
        // Computation of the interpolated normal vector
        const barycentric_info bary = get_barycentric(p);
        const orientation_type ray_orientation = is_negative(r.direction | normal) ?
              orientation_type::Inward
            : orientation_type::Outward;

        return hit(pt_ray, p, get_interpolated_normal(bary), pt_obj, ray_orientation);
    }
    else { // Flat shading

        return hit(pt_ray, p, normal, pt_obj);
    }
}

/* Minimum and maximum coordinates */
min_max_coord quad::get_min_max_coord() const {

    const rt::vector p1 = position + v1;
    const rt::vector p2 = position + v2;
    const rt::vector p3 = position + v3;

    return {
        .min_x = std::min(position.x, std::min(p1.x, std::min(p2.x, p3.x))),
        .max_x = std::max(position.x, std::max(p1.x, std::max(p2.x, p3.x))),

        .min_y = std::min(position.y, std::min(p1.y, std::min(p2.y, p3.y))),
        .max_y = std::max(position.y, std::max(p1.y, std::max(p2.y, p3.y))),
        
        .min_z = std::min(position.z, std::min(p1.z, std::min(p2.z, p3.z))),
        .max_z = std::max(position.z, std::max(p1.z, std::max(p2.z, p3.z)))
    };
}

/* Prints the quad */
void quad::print() const {
    printf("p0 = (%lf, %lf, %lf), ", position.x, position.y, position.z);
    rt::vector p1 = position + v1;
    printf("p1 = (%lf, %lf, %lf), ", p1.x, p1.y, p1.z);
    rt::vector p2 = position + v2;
    printf("p2 = (%lf, %lf, %lf)\n", p2.x, p2.y, p2.z);
    rt::vector p3 = position + v3;
    printf("p3 = (%lf, %lf, %lf)\n", p3.x, p3.y, p3.z);
}

/* Normal map vector computation at render time
    Local normal may be the normal of the quad (for flat shading) or the smoothed normal, and in this case the tangent space should be reorthonormalized */
rt::vector quad::compute_normal_from_map(const rt::vector& tangent_space_normal, const rt::vector& local_normal, const texture_info& info) const {

    if constexpr (SHADING == shading::SmoothShading) {
        const rt::vector& t = info.tangent;
        
        // Recompute the tangent space with Gram-Schmidt's method
        /*
        const rt::vector t2 = (t - ((t | local_normal) * local_normal)).unit();
        const rt::vector b2 = t2 ^ local_normal;

        //return tangent_space_normal.x * t2 + tangent_space_normal.y * b2 + tangent_space_normal.z * local_normal;
        return matprod(
            t2,             tangent_space_normal.x,
            b2,             tangent_space_normal.y,
            local_normal,   tangent_space_normal.z
        );
        */
        const rt::vector t2_non_unit = t - ((t | local_normal) * local_normal);
        const rt::vector b2_non_unit = t2_non_unit ^ local_normal;
        const real norm_t2 = t2_non_unit.norm();

        //return tangent_space_normal.x * t2 + tangent_space_normal.y * b2 + tangent_space_normal.z * local_normal;
        return matprod(
            t2_non_unit,  tangent_space_normal.x / norm_t2,
            b2_non_unit,  tangent_space_normal.y / norm_t2,
            local_normal, tangent_space_normal.z
        );
    }
    else {
        // Flat shading
        const rt::vector& t = info.tangent;
        const rt::vector& b = info.bitangent;

        //return tangent_space_normal.x * t + tangent_space_normal.y * b + tangent_space_normal.z * local_normal;
        return matprod(t, b, local_normal, tangent_space_normal);
    }

}


rt::vector quad::sample(const randomgen& rg) const {

    // Choosing lower or upper triangle with probability proportional to their area
    const rt::vector& vi = (rg.random_ratio() < ratio) ? v1 : v3;

    return triangle::sample_triangle(rg, position, vi, v2);
}

rt::vector quad::sample_visible(const randomgen& rg, const rt::vector& /*pt*/) const {
    
    return sample(rg);
}